### ISSUE TITLE
Error:No module named 'utils.training_sdg_inner'

### ISSUE THREAD

**Issue by kevin-meng** [vwz/ComE#1]
hello i am try to run the project,but failed and the error goes as :
 
2019-05-05 03:50:29 ERROR context_embeddings.py: 18 No module named 'utils.training_sdg_inner'
Traceback (most recent call last):
  File "/media/kevin/storage1/JupyterNotebook/GraphEmbedding/Git/ComE/main.py", line 12, in <module>
    from ADSCModel.context_embeddings import Context2Vec
  File "/media/kevin/storage1/JupyterNotebook/GraphEmbedding/Git/ComE/ADSCModel/context_embeddings.py", line 19, in <module>
    raise e
  File "/media/kevin/storage1/JupyterNotebook/GraphEmbedding/Git/ComE/ADSCModel/context_embeddings.py", line 15, in <module>
    from utils.training_sdg_inner import train_o2, loss_o2, FAST_VERSION
ModuleNotFoundError: No module named 'utils.training_sdg_inner'

-----------------------------------
i have try to degug it but failed , could you help me to fix this ? thank you

**Comment by vaudaine** [comment]
Hello, 
I successfully installed comE today.

1) Install Cython==0.25 
2) In comE-master, run: 'python3 cython_utils.py build_ext'
A new directory 'build' will be created. 
3) Navigate the directories and find training_sdg_inner.cpython-36m-x86_64-linux-gnu.so and training_sdg_inner.o. Copy and paste both files to the comE-master/utils/ directory.
4) run: 'python3 main.py'
You can also edit main.py to change the parameters at your will.

Rémi

**Comment by LXXiaogege** [comment]
Thank for your answer，vaudaine.
his steps is true，and i add a key point，
read the env.yml file carefully，python package version is focus for bug.
